import React, { Component } from "react";

class MainContent extends Component{
  // let { personal } = this.props.userProfile;
  // console.log(this.props)
    render(){
      console.log(this.props);
        return(
          <dvi>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            <p>Main Content</p>
            </dvi>
        );
    }
};

export default MainContent;
